version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - .docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  composer:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: composer install